Std.source.response(function(){
    function CSSFile_UI(name){
        return "ui/theme/default/" + name + ".css";
    }
    function JSFile_UI(name){
        return "ui/" + name + ".js";
    }
    return {
        "Image":JSFile_UI("ui.Image"),
        "Label":JSFile_UI("ui.Label"),
        "Item":JSFile_UI("ui.Item"),
        "CheckBox":[
            CSSFile_UI("ui.CheckBox"),
            JSFile_UI("ui.CheckBox")
        ],
        "RadioBox":[
            CSSFile_UI("ui.RadioBox"),
            JSFile_UI("ui.RadioBox")
        ],
        "SwitchBox":[
            CSSFile_UI("ui.SwitchBox"),
            JSFile_UI("ui.SwitchBox")
        ],
        "LineEdit":[
            CSSFile_UI("ui.Edit"),
            JSFile_UI("ui.Edit")
        ],
        "Button":[
            CSSFile_UI("ui.Button"),
            JSFile_UI("ui.Button")
        ],
        "Canvas":[
            JSFile_UI("ui.Canvas")
        ],
        "ColorPicker":[
            CSSFile_UI("ui.ColorPicker"),
            JSFile_UI("ui.ColorPicker")
        ],
        "DatePicker":[
            CSSFile_UI("ui.DatePicker"),
            JSFile_UI("ui.DatePicker")
        ],
        "List":[
            CSSFile_UI("ui.List"),
            JSFile_UI("ui.List")
        ],
        "Menu":[
            CSSFile_UI("ui.Menu"),
            JSFile_UI("Menu")
        ],
        "MenuBar":[
            CSSFile_UI("ui.MenuBar"),
            JSFile_UI("ui.MenuBar")
        ],
        "ComboBox":[
            CSSFile_UI("ui.ComboBox"),
            JSFile_UI("ui.ComboBox")
        ],
        "ToolBar":[
            CSSFile_UI("ui.ToolBar"),
            JSFile_UI("ui.ToolBar")
        ],
        "Panel":[
            CSSFile_UI("ui.Panel"),
            JSFile_UI("ui.Panel")
        ],
        "Window":[
            CSSFile_UI("ui.Window"),
            JSFile_UI("ui.Window")
        ],
        "MessageBox":[
            CSSFile_UI("ui.MessageBox"),
            JSFile_UI("ui.MessageBox")
        ],
        "Pagination":[
            CSSFile_UI("ui.Pagination"),
            JSFile_UI("ui.Pagination")
        ],
        "Progress":[
            CSSFile_UI("ui.Progress"),
            JSFile_UI("ui.Progress")
        ],
        "Accordion":[
            CSSFile_UI("ui.Accordion"),
            JSFile_UI("ui.Accordion")
        ],
        "Tabs":[
            CSSFile_UI("ui.Tabs"),
            JSFile_UI("ui.Tabs")
        ],
        "Slider":[
            CSSFile_UI("ui.Slider"),
            JSFile_UI("ui.Slider")
        ],
        "Tree":[
            CSSFile_UI("ui.Tree"),
            JSFile_UI("ui.Tree")
        ],
        "GridView":[
            CSSFile_UI("ui.GridView"),
            JSFile_UI("ui.GridView")
        ],
        "PropertyGird":[
            CSSFile_UI("ui.PropertyGird"),
            JSFile_UI("ui.PropertyGird")
        ],
        "Video":[
            CSSFile_UI("ui.Video"),
            JSFile_UI("ui.Video")
        ]
  };
});